version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    restart: always
    environment:
      ORACLE_PASSWORD: oracle_password
      ORACLE_DATABASE: orcl
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
    driver: local
